### ISSUE TITLE
would u like join BFBAN developer organization?

### ISSUE THREAD

**Issue by SoraKasvgano** [3N7R0PY1337/auto-space#1]
https://github.com/BFBAN

Battlefield Player Community Self-founded Non-Profit Anti Hacker Developer Organization.

our website is opensource，https://github.com/mygoare/bfban ,here is the source code...

it can track hacker's ID,even hacker changed his origin ID name....

record his hacker history in battlefield series......

hope we can develop it  together lol

**Comment by SoraKasvgano** [comment]
oh site's address is www.bfban.com

**Comment by asix1337** [comment]
Thanks for the request, but its useless because EA don't want to ban any of them.

**Comment by SoraKasvgano** [comment]
> Thanks for the request, but its useless because EA don't want to ban any of them.

sad, indeed................

hope this site can collect data, in order to ban hacker in future BF series,If next BF could offer API / WEB admin like BF3 BF4

**Comment by asix1337** [comment]
We will see, maybe i give you an replay.
